### ISSUE TITLE
Many thanks and more entries to remove the malware entries.

### ISSUE THREAD

**Issue by ibay770** [skidaim/TJprojMain-explorer.exe-remover#1]
First of all, many thanks for writing your script to get rid of this trash.
From this video (https://www.youtube.com/watch?v=GsIl33z8B2Q) it seems the virus leaves behind registry entries of infected files, even once the original is deleted.  
Assuming I wrote the commands correctly, I think this script will delete those, perhaps you could merge it to your script.

the /f deletes the key without asking for confirmation.

reg delete "HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\BagMRU" /f
reg delete "HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags" /f
reg delete "HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache" /f

**Comment by ibay770** [comment]
Also here is a malware analysis from any.run if it helps.:

[https://any.run/report/556e510eac2c4f61e6a5530cda4004a1976a79c4f46a02e2488ad79207274f0e/347d855d-a849-4c2a-829f-59b26c4b3d1c#Network](https://any.run/report/556e510eac2c4f61e6a5530cda4004a1976a79c4f46a02e2488ad79207274f0e/347d855d-a849-4c2a-829f-59b26c4b3d1c#Network)

**Comment by ibay770** [comment]
My pleasure! I'll take a look. As you see, this malware hooks itself into other files so it reinfects the computer when they run, is there a way to disinfect said files and delete the infected ones as well? Another way of getting rid of it, is to run [UVK](https://www.carifred.com/uvk/) use the autorun setting, click the explorer/svchost entries and click delete files and entries, then go back, and immunize the system, make sure all boxes are checked, apply, restart the system, and all is good,

**Comment by tee4341** [comment]
I can't find stinker.exe to clone. .exe remove (Detail tjprojmain.exe) I can't compile byte_stinker-1.1
![screenshot 2022-09-18](https://user-images.githubusercontent.com/48321898/190876621-7dc541bb-a6c7-4d0a-ac34-851704b40f18.jpg)

**Comment by ibay770** [comment]
https://github.com/ibay770/byte_stinker/releases/download/0.1/byte_stinker-1.1.zip
