### ISSUE TITLE
 I can't find stinker.exe to clone. .exe  remove (Detail tjprojmain.exe) 

### ISSUE THREAD

**Issue by tee4341** [skidaim/TJprojMain-explorer.exe-remover#2]
I can't find stinker.exe to clone. .exe  remove (Detail tjprojmain.exe)       
![screenshot 2022-09-18](https://user-images.githubusercontent.com/48321898/190881835-6852c4ee-5e9f-418c-82cb-cdd5fee0eeec.jpg)
I can't compile byte_stinker-1.1
![screenshot 2022-09-18 (1)](https://user-images.githubusercontent.com/48321898/190881839-53c07e75-5017-4d30-9f1a-28f4632b3852.jpg)

**Comment by autumnlikescode** [comment]
Here you go, it needs to be compiled in Visual Studio 
[Release.zip](https://github.com/skidaim/TJprojMain-explorer.exe-remover/files/9691810/Release.zip)
